FROM nginx:alpine

# Copy Nginx configuration file
COPY ./default.conf /etc/nginx/conf.d/default.conf

# Copy SSL certificate and key
COPY ./nginx.crt /etc/nginx/ssl/nginx.crt
COPY ./nginx.key /etc/nginx/ssl/nginx.key

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]